version: "3.3"

services:
    flow:
      image: "quay.io/hazelcast_cloud/hazelcast-flow-internal:next"
      healthcheck:
        test: curl --fail http://localhost:9021/api/actuator/health || exit 1
        interval: 30s
        timeout: 5s
        retries: 3
      environment:
         MC_LICENSE: "${MC_LICENSE}"
         JAVA_OPTS: >-
            -Xms256m
            -Xmx1024m
         OPTIONS: >-
            --vyne.analytics.persistRemoteCallResponses=true
            --vyne.analytics.persistResults=true
            --vyne.db.database=flow
            --vyne.db.username=flow
            --vyne.db.password=changeme
            --vyne.db.host=postgres
            --vyne.security.openIdp.enabled=true
            --vyne.security.openIdp.jwks-uri=http://management-center:8080/oauth2/jwks
            --vyne.security.openIdp.issuerUrl=http://localhost:8080
            --vyne.security.openIdp.clientId=flow-client
            --vyne.security.openIdp.require-https=false
            --vyne.security.open-idp.roles.format=path
            --vyne.security.open-idp.roles.path=roles
            --vyne.config.custom.managementCenterUrl=http://localhost:8080
            --vyne.workspace.project-file=/opt/service/workspace/taxi.conf
#            If you're using a workspace, rather than a single-project config,
#           use this option.
#            --vyne.workspace.config-file=/opt/service/workspace/workspace.conf
      ports:
         - "9021:9021"
      expose:
         - 9021
      volumes:
         - ~/.hazelcast/flow/license/:/opt/var/vyne/license/
         - ./workspace:/opt/service/workspace
      depends_on:
         - postgres
      deploy:
         resources:        
            limits:
               memory: 1024M
            reservations:
               cpus: '2'
               memory: 1024M

    management-center:
      image: "docker.io/hazelcast/management-center-flow:${MC_FLOW_VERSION}"
      ports:
        - "8080:8080"
      healthcheck:
        test: curl --fail http://localhost:8080/health || exit 1
        interval: 30s
        timeout: 5s
        retries: 3
      environment:
        - JAVA_OPTS=-Dhazelcast.mc.flow.address=http://localhost:9021 -Dhazelcast.mc.flow.internalAddress=http://hazelcast-flow:9021
        - MC_DEFAULT_CLUSTER=flow
        - MC_DEFAULT_CLUSTER_MEMBERS=flow:25701
        - MC_LICENSE=${MC_LICENSE}
        - MC_INIT_CMD=./bin/mc-conf.sh security reset && ./bin/mc-conf.sh user create -n admin -r admin -p "changeMe!135" && ./bin/mc-conf.sh user create -n user -r readwrite -p "changeMe!135" && ./bin/mc-conf.sh user create -n readonly -r readonly -p "changeMe!135" && ./bin/mc-conf.sh user create -n metricsonly -r metricsonly -p "changeMe!135"

    postgres:
      image: postgres:15
      expose:
         - 5432
      ports:
         - "25432:5432"
      environment:
         POSTGRES_DB: flow
         POSTGRES_USER: flow
         POSTGRES_PASSWORD: changeme
      volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data:
