version: "3.3"

services:
    hazelcast:
        image: docker.io/hazelcast/hazelcast:${HZ_VERSION:-latest}
        ports:
        - "5701-5703:5701"
        deploy:
            replicas: 3
            endpoint_mode: dnsrr
        environment:
            - HZ_MANAGEMENTCENTER_CONSOLEENABLED=true
            - HZ_MANAGEMENTCENTER_SCRIPTINGENABLED=true

    flow:
      image: docker.io/hazelcast/hazelcast-flow:${FLOW_VERSION:-latest-snapshot}
      healthcheck:
        test: curl --fail http://localhost:9021/api/actuator/health || exit 1
        interval: 30s
        timeout: 5s
        retries: 3
      environment:
         MC_LICENSE: "${MC_LICENSE}"
         JAVA_OPTS: >-
            -Xms256m
            -Xmx1024m
         OPTIONS: >-
            --flow.analytics.persistRemoteCallResponses=true
            --flow.analytics.persistResults=true
            --flow.hazelcast.addresses=hazelcast:5701
            --flow.hazelcast.cluster-name=dev
            --flow.db.database=flow
            --flow.db.username=flow
            --flow.db.password=changeme
            --flow.db.host=postgres
            --flow.config.custom.managementCenterUrl=http://localhost:8080
            --flow.workspace.project-file=/opt/service/workspace/taxi.conf
#            If you're using a workspace, rather than a single-project config,
#           use this option.
#            --flow.workspace.config-file=/opt/service/workspace/workspace.conf
      ports:
         - "9021:9021"
      expose:
         - 9021
      volumes:
         - ~/.hazelcast/flow/license/:/opt/var/flow/license/
         - ./workspace:/opt/service/workspace
      depends_on:
         - postgres
      deploy:
         resources:        
            limits:
               memory: 1024M
            reservations:
               cpus: '2'
               memory: 1024M

    management-center:
      image: docker.io/hazelcast/management-center-flow:${MC_VERSION:-latest}
      ports:
        - "8080:8080"
      healthcheck:
        test: curl --fail http://localhost:8080/health || exit 1
        interval: 30s
        timeout: 5s
        retries: 3
      environment:
        - JAVA_OPTS=-Dhazelcast.mc.flow.address=http://localhost:9021 -Dhazelcast.mc.flow.internalAddress=http://flow:9021
        - MC_DEFAULT_CLUSTER=flow
        - MC_DEFAULT_CLUSTER_MEMBERS=flow:25701
        - MC_LICENSE=${MC_LICENSE}
        - MC_INIT_CMD=./bin/mc-conf.sh security reset

    postgres:
      image: postgres:15
      expose:
         - 5432
      ports:
         - "25432:5432"
      environment:
         POSTGRES_DB: flow
         POSTGRES_USER: flow
         POSTGRES_PASSWORD: changeme
      volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data:
